### PR TITLE
Fix cmake build: use target_link_libraries instead of LINK_FLAGS

### PR DESCRIPTION
**Pull request by rljacobuc**
LINK_FLAGS places library flags before object files in the linker command, causing undefined reference errors with GNU ld which requires libraries to appear after the object files that use them.

Replace LINK_FLAGS with target_link_options (for rpath) and target_link_libraries (for wxWidgets and NetCDF libraries) so that the link order is correct.

### CODE REVIEW

**Comment by rljacob** [comment]
@copilot make a PR to apply changes based on the comments in [this thread](https://github.com/SEATStandards/ncvis/pull/26#pullrequestreview-3900242286)

**Comment by rajeeja** [comment]
Hi @rljacobuc — the token-by-token split separates "-framework" from the framework name, so macOS ends up with either -lCocoa or a bare "Cocoa" on the link line once target_link_options de-duplicates the repeated -framework tokens. Pushed a commit using wxWidgets_LIBRARIES and NETCDF_LIBRARIES from the find_package calls already in the top-level CMakeLists instead, which keeps those pairs intact. Checked your Linux case still works in an Ubuntu 24.04 container with GNU ld so I think this is good to go now.

**Review by rajeeja — APPROVED** [review]
Tested on macOS 26 with AppleClang and on Ubuntu 24.04 with GNU ld 2.42 in a container: undefined reference to wxFrameNameStr before this, clean build after, on both. Frameworks stay paired on the macOS link line and object files come before libraries on Linux.
